[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10 
padding.y = 10 

[font]
size = 16.0

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font"
style = "Regular"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[selection]
save_to_clipboard = true

