[general]
live_config_reload = true
# import = ["./one_dark.toml"]
import = ["./tokyo_night.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 10 
padding.y = 10 
opacity = 0.9
blur = true
option_as_alt = "OnlyLeft"

[font]
size = 16.0

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.bold]
family = "GeistMono Nerd Font"
style = "Regular"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[selection]
save_to_clipboard = true
