# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Moonfly theme
# https://github.com/bluz71/vim-moonfly-colors/blob/master/extras/moonfly-starship.toml
palette = "moonfly"

[c]
style = "green"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "fern"

[git_branch]
style = "lavender"

[package]
style = "orange"

[perl]
style = "green"

[swift]
style = "red"

[terraform]
style = "purple"

[palettes.moonfly]
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"
red = "#f07496"

