#!/bin/zsh

## Update Homebrew 
echo "Updating Homebrew ..."
echo ""
brew update 

echo "Updating Homebrew Packages..."
echo ""
brew upgrade

echo "Cleaning Homebrew ..."
echo ""
brew cleanup --prune=all
brew autoremove 

echo ""
echo "You are up to date!!!"
